openaire_dump:
  path_raw: data/pile/openaire_2025_12_01_dump
  path_duck: data/duckdb/sources/openaire_raw.duckdb
  path_duck_staging_2: data/duckdb/sources/openaire_staging_2.duckdb
openalex_dump:
  path_raw: data/pile/openalex_2026_02_03_dump
  path_duck: data/duckdb/sources/openalex_raw.duckdb
ror_dump:
  path_raw: data/pile/ror_2026_08_03_dump/v2.11-2026-08-03-ror-data.json
  path_duck: data/duckdb/sources/ror_raw.duckdb
minorities:
  path_raw: data/pile/minorities/minorities.csv
  path_duck: data/duckdb/sources/minorities_raw.duckdb
  path_duck_staging: data/duckdb/sources/minorities_staging.duckdb
  path_duck_staging_2: data/duckdb/sources/minorities_staging_2.duckdb
  path_duck_terms: data/duckdb/sources/minorities_terms.duckdb
